### ISSUE TITLE
ART - double check title search

### ISSUE THREAD

**Issue by lpalbou** [geneontology/noctua-annotation-review#44]
During hands on call, Karen was looking at PMID-27340223-krc . On her spreadsheet, there was two models with that same title (the second one having a bit more info). Double check if noctua dev had both models or only one.

**Comment by vanaukenk** [comment]
If I search with the PMID on noctua or noctua-dev using the Reference field, I get four models returned:

![image](https://user-images.githubusercontent.com/1730534/118289112-0286f500-b4a3-11eb-92a3-4278d8d07a36.png)

I'd need more info from Karen about exactly what the expected model titles are so we can see what the issue is here.

**Comment by vanaukenk** [comment]
@lpalbou checked the models repository and there are two models with PMID:27340223 in the title, although one has a ':' and one has a '-' between 'PMID' and the identifier.
We still need to investigate further to understand, though, why both models cannot be returned from either a title or reference filter from the Noctua landing page.
@lpalbou and @tmushayahama have some theories; it could be related to the known models save issue or models not being ingested back into blazegraph.

**Comment by lpalbou** [comment]
Ok turns out the model 468 was deleted...
https://github.com/geneontology/noctua-models/blob/11e35492993c59eae3856bafc22aa3105ff223cd/models/5900dc7400000468.ttl#L10

Hence not ingested in Noctua, and not searchable as it should... closing this issue as everything is working as expected. @vanaukenk or @ukemi to report back to Karen.
